<script lang="ts">
	import formModel from '$lib/models/formModel';

	let files: FileList = $state();
	let isDragging = $state(false);
	let isSelected = false;

	function onDragOver(event: DragEvent) {
		isDragging = true;
		event.preventDefault();
	}

	function onDragLeave(event: DragEvent) {
		isDragging = false;
	}

	function onDrop(event: DragEvent) {
		isDragging = false;
		event.preventDefault();

		let items = event.dataTransfer?.files;

		if (items !== undefined) {
			files = items;
		}
	}

	function fileChange(event) {
		// Reset to null so using the same file multiple times works
		event.target.value = null;
	}

	$effect(() => {
		if (files) {
			if (files.length < 1) {
				// Do nothing.
				//
				// If you open the file input window then close it, you get an empty file
				// list which can trigger this code. If this code was triggered with no
				// files just ignore it
			} else if (files.length > 1) {
				alert('Please only provide a single file.');
			} else {
				formModel.readConfig(files[0]);
			}
		}
	});
</script>

<!-- I couldn"t find a good answer for what ARIA role to give this, but the
  linter told me I needed one -->
<div
	id="dropzone"
	class:isDragging
	class:isSelected
	ondragover={onDragOver}
	ondragleave={onDragLeave}
	ondrop={onDrop}
	role="button"
	tabindex="0"
>
	<input
		id="dropinput"
		bind:files
		onchange={(event) => fileChange(event)}
		type="file"
		accept=".toml"
	/>
	<div class="text-center text-xl text-gray-700">
		<h1 class="mt-2.5 mb-1 text-4xl">Drag and drop or click here</h1>
		Load a config to prefill the form.<br />Note: configs not generated by this webapp are not
		guaranteed to work.
	</div>
</div>

<style lang="postcss">
	@reference "tailwindcss";

	#dropzone {
		box-shadow: rgb(153, 153, 153) 5px 5px 5px;
		@apply relative mb-4 w-full rounded-lg border-4 border-dashed border-gray-300 bg-gray-100 p-12;
	}

	#dropzone.isDragging {
		@apply border-solid font-bold shadow-inner;
	}

	#dropinput {
		@apply absolute top-0 right-0 bottom-0 left-0 h-full w-full cursor-pointer opacity-0;
	}
</style>
